### ISSUE TITLE
Upload dataset

### ISSUE THREAD

**Issue by Bennykillua** [Bennykillua/Pyspark-Online-Job-Postings#5]
Upload this [dataset](https://www.kaggle.com/datasets/madhab/jobposts) in [here](https://github.com/Bennykillua/Pyspark-Online-Job-Postings/tree/main/Dataset)

**Comment by sarthakw7** [comment]
Can I work on this?

**Comment by Bennykillua** [comment]
Yeah someone just worked on it @sarthakw7 Thanks
